config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  post 'graphql' => 'graphqls#create'
  get '/pages/*id' => 'pages#show', as: :page, format: false

  resource :dashboard, only: :show

  namespace :talk_summaries do
    resource :top
  end

  resources :talk_summaries, only: %w[create index show]

  root 'pages#index'
end

app/models/talk_summary.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: talk_summaries
#
#  id                   :integer          not null, primary key
#  body                 :string           not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  submitted_by_user_id :integer          not null
#  submitted_at         :datetime         not null
#  talk_id              :integer          not null
#
# Indexes
#
#  index_talk_summaries_on_submitted_by_user_id  (submitted_by_user_id)
#  index_talk_summaries_on_talk_id               (talk_id)
#
# Foreign Keys
#
#  fk_rails_2fd0d122c7  (talk_id => talks.id)
#  fk_rails_5220d05fed  (submitted_by_user_id => users.id)
#

class TalkSummary < ApplicationRecord
  validates :body, presence: true
  validates :submitted_at, presence: true

  belongs_to :submitted_by_user, class_name: 'User'
  belongs_to :talk

  delegate :title, :presenter, :event, :youtube_embed_url, to: :talk
end

app/controllers/talk_summaries/tops_controller.rb
# frozen_string_literal: true
module TalkSummaries
  class TopsController < ApplicationController
    def show
      @top_talks = [
        {
          title: 'Rails Conf 2017: Keynote',
          speaker: 'Aaron Patterson',
          summary: 'Aaron talks about Rails.',
          tags: %w[cats dogs]
        },
        {
          title: 'Rails Conf 2017: Opening Keynote',
          speaker: 'David Heinemeier Hansson',
          summary: 'DHH talks about Rails.',
          tags: %w[cats dogs]
        }
      ]

      render 'talk_summaries/top'
    end
  end
end

app/controllers/talk_summaries_controller.rb
# frozen_string_literal: true
class TalkSummariesController < ApplicationController
  def create
    @talk_summary = TalkSummaries::CreateService.new(
      permitted_create_params.to_h.merge(submitted_by_user: current_user).symbolize_keys
    ).call

    if @talk_summary.valid?
      flash[:notice] = 'Summary created!'
    else
      flash[:error] = 'Something went wrong.'
    end

    redirect_to dashboard_path
  end

  def index
    @talk_summaries = TalkSummary.includes(:talk).all
  end

  def show
    @talk_summary = TalkSummary.find(params[:id])
  end

  private

  def permitted_create_params
    params.require(:talk_summary).permit(
      :video_url,
      :title,
      :body
    )
  end
end

app/views/talk_summaries/index.html.slim
h1 All Talks

table.table
  thead
    tr
      th Talk Title
      th Presenter
      th Conference
  tbody
    - @talk_summaries.each do |talk_summary|
      tr
        td
          = link_to(talk_summary.title, talk_summary_path(talk_summary.id))
        td= talk_summary.presenter
        td= talk_summary.event

app/views/talk_summaries/show.html.slim
.container
  .columns
    .column
      .content.has-text-centered
        iframe style="margin: 0 auto; display: block;" allow="encrypted-media" allowfullscreen="" frameborder="0" gesture="media" height="480" src="#{@talk_summary.youtube_embed_url}" width="854" 
        div
          <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.
  .columns
    .column
      .content
        hr
        = Utilities::Markdown.new(text: @talk_summary.body).call

app/views/talk_summaries/top.html.slim
h1 Top Talks
- @top_talks.each do |talk|
  p
    strong= talk[:title]
    | &nbsp;#{talk[:speaker]}
  p
    - talk[:tags].each do |tag|
      span.badge.badge-pill.badge-primary.mr-1= tag
  p= talk[:summary]