config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  post 'graphql' => 'graphqls#create'
  get '/pages/*id' => 'pages#show', as: :page, format: false

  resource :dashboard, only: :show

  namespace :talk_summaries do
    resource :top
  end

  resources :talk_summaries, only: %w[create index show]

  root 'pages#index'
end

app/views/shared_views/_footer.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to('Programming Talk Summaries', root_path, class: 'navbar-brand')

app/views/shared_views/_meta.html.slim
meta[name="viewport" content="width=device-width, initial-scale=1.0"]
title
  = content_for?(:title) ? yield(:title) : 'Transcripto'
meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Transcripto'}"
== stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css"
== stylesheet_link_tag "https://afeld.github.io/emoji-css/emoji.css"
== javascript_pack_tag 'application'
== stylesheet_pack_tag 'styles/app'
== csrf_meta_tags

app/views/shared_views/_navigation.html.slim
nav.Site-Header.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to('Programming Talk Summaries', root_path, class: 'navbar-brand')
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li(class="#{active_nav_class(root_path)}")
        = link_to('Home', root_path, class: 'nav-link')
      li(class="#{active_nav_class(talk_summaries_top_path)}")
        = link_to('All', talk_summaries_path, class: 'nav-link')
      li(class="#{active_nav_class(talk_summaries_top_path)}")
        = link_to('Top', talk_summaries_top_path, class: 'nav-link')
      li.nav-item
        = link_to('About', page_path('about'), class: 'nav-link')
    div
      - if user_signed_in?
        = link_to('Log Out', destroy_user_session_path)
      - else
        = link_to('Log In', new_user_session_path)

app/views/shared_views/_sidebar.html.slim
aside.main-sidebar.column
  /! sidebar: style can be found in sidebar.less
  section.sidebar
    /! sidebar menu: : style can be found in sidebar.less
    ul.sidebar-menu
      li.header MAIN NAVIGATION
      li.active.treeview
        a href="#"
          i.fa.fa-laptop
          span QA Tools
          span.pull-right-container
            i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          li.active
            a href="/admin/scores"
              i.fa.fa-circle-o
              | Score Testing Tool
          li
            a href="/admin/scenarios"
              i.fa.fa-circle-o
              | Scenario Analysis
          li
            a href="/admin/matches"
              i.fa.fa-circle-o
              | Match JSON Viewer
      li
        = link_to '/api-docs/index.html'
          i.fa.fa-book
          span API Docs